### ISSUE TITLE
omnitron

### ISSUE THREAD

**Issue by s0m3on3** [ciferox/adone#2]
1. Wrong config paths references, omnitron cant start

`src/omnitron/index.js:30`
```js
lazify({
    Service: "./service",
    Omnitron: "./omnitron",
    DB: "./omnitron/db",
    Dispatcher: "./dispatcher",
    dispatcher: () => new adone.omnitron.Dispatcher(),
    port: () => (is.windows ? `\\\\.\\pipe\\${adone.realm.config.realm}\\omnitron.sock` : adone.std.path.join(adone.realm.config.runtimePath, "omnitron.sock"))
}, adone.asNamespace(exports), require);
```
`src/omnitron/dispatcher.js:125`
```js
const omniConfig = adone.realm.config.omnitron;
await adone.fs.mkdirp(std.path.dirname(omniConfig.logFilePath));
this.descriptors.stdout = std.fs.openSync(omniConfig.logFilePath, "a");
this.descriptors.stderr = std.fs.openSync(omniConfig.errorLogFilePath, "a");
const args = [std.path.resolve(adone.ROOT_PATH, "lib/omnitron/omnitron/index.js")];
```

Maybe there are more of them, but after fixes for these parts omnitron starts

2. Errors thrown in a service initializer (like pm) crashes the whole omnitron.
Maybe it happened due to an unhandled exception
```
src/glosses/errors/index.js:199
    const err = new idExceptionMap[id](message);
                ^
TypeError: idExceptionMap[id] is not a constructor
    at Object.create (src/glosses/errors/index.js:199:17)
    at Object.decodeException [as decode] (src/glosses/data/mpak.js:572:28)
    at Decoder._decodeExt (src/glosses/data/mpak.js:482:43)
    at Decoder.tryDecode (src/glosses/data/mpak.js:394:29)
    at Decoder._decodeMap (src/glosses/data/mpak.js:442:42)
    at Decoder.tryDecode (src/glosses/data/mpak.js:412:25)
    at Decoder._decodeArray (src/glosses/data/mpak.js:462:39)
    at Decoder.tryDecode (src/glosses/data/mpak.js:408:25)
    at Decoder._decodeArray (src/glosses/data/mpak.js:462:39)
    at Decoder.tryDecode (src/glosses/data/mpak.js:408:25)
```
A native node error was thrown. Like
```js
adone.std.path.resolve(null)
```

**Comment by maxveres** [comment]
not actual
